version: '3.1'
services:
  ewm-service:
    image: ewm-service
    build: main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-service-db:5432/ewm-service
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
  stats-server:
    image: ewm-stats-server
    build: stats-service/stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  stats-db:
    image: postgres:15.1-alpine
    container_name: ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
  ewm-service-db:
    image: postgres:15.1-alpine
    container_name: ewm-service-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewm-service
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm



