version: '3.1'
services:
  stats-server:
    image: ewm-stats-server
    build: stats-service/stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  stats-db:
    image: postgres:15.1-alpine
    container_name: ewm-stats-db
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm



